# Generated by Django 4.2 on 2023-05-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
