# Generated by Django 4.2.1 on 2023-06-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0010_cart_wishlist_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
